version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - ga-runners
    volumes:
      - "./redis-data:/data"

  # postgres:
  #   image: postgres:17.0
  #   container_name: postgres
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #   networks:
  #     - ga-runners
  #   volumes:
  #     - "./postgres-data:/var/lib/postgresql/data"

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - ga-runners
    volumes:
     - "./mongo-data:/data/db"

  # localstack:
  #   container_name: localstack
  #   image: localstack/localstack
  #   ports:
  #     - "127.0.0.1:4566:4566"
  #     - "127.0.0.1:4510-4559:4510-4559"
  #   environment:
  #     - DEBUG=0
  #   volumes:
  #     - "./localstack:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   networks:
  #     - ga-runners


networks:
  ga-runners:
    driver: bridge
