version: '3.8'

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - ga-runners
    volumes:
      - "./redis-data:/data"

  mongo:
    image: mongo:8.0.3
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    networks:
      - ga-runners
    volumes:
     - "./mongo-data:/data/db"

networks:
  ga-runners:
    driver: bridge
